version: '3'

services:
  server:
    image: shoambendavid/github-mastery-server:latest
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5001
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  client:
    image: shoambendavid/github-mastery-client:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: always
    depends_on:
      - server

volumes:
  mongodb_data: 